### ISSUE TITLE
Overview of all fields filled in

### ISSUE THREAD

**Issue by ingrre** [HumanBrainProject/ebrains_wizard#4]
Could we get a full overview of all fields filled in by the data provider (e.g. in html), such as the non-imported fields are visualised now?

**Comment by eapapp** [comment]
This needs the following steps to be completed:

- [x] CSS adjustments for displaying the two tables
- [x] New mapping of KG and offline fields based on formData
- [x] Adding human-readable labels for the fields license & preparationType
- [x] Adjustments in table generation

**Comment by eapapp** [comment]
The JSON uploader script is now updated to display two tables: 1) KG-compatible fields, 2) Other fields. Please update your version from the [Curation GitLab](https://kanban.ebrains.eu/curators/ebrains-curation-team/-/tree/master/metadata-wizard-json).

![two-tables-preview](https://user-images.githubusercontent.com/55808942/173328584-a8193965-7ee9-48dd-86c7-a5f1e135997a.png)
