### ISSUE TITLE
Submit JSON directly to the curation team

### ISSUE THREAD

**Issue by eapapp** [HumanBrainProject/ebrains_wizard#6]
Let users submit their metadata JSON directly to curators instead of having to download and send it over e-mail.

Suggested by @blixilla during the NeSys workshop. Thank you! 🙏🏻

**Comment by ehennestad** [comment]
One solution is to set up a backend running a pyflask application (on OpenShift or external server?) that can send the json to the curation team’s email (Thanks to Harry (@PolarBean) for coming up with this idea and making a practical demo).

**Comment by eapapp** [comment]
Thank you @ehennestad and @PolarBean! I think we should be able to do this without hosting another app though. More reliable to do it directly from the Node.js app that is serving the wizard. Just a [few things to set up](https://www.w3schools.com/nodejs/nodejs_email.asp).

Need to think about who the sender should be 🤔 We could do it via EBRAINS or via a service account of our own.

**Comment by ehennestad** [comment]
Yes, that looks like a cleaner option!
Can we get an email account like metadata-submission@humanbrainproject.eu / metadata-submission@ebrains.eu

Also, if we want to send an immediate confirmation to the data provider, we might want an additional account like noreply@humanbrainproject.eu / noreply@ebrains.eu

**Comment by eapapp** [comment]
I was thinking we could direct the e-mails to Zammad (curation-support@ebrains.eu). That way they should end up in the Share data group and not spam others than the curation team.
no-reply@ebrains.eu already exists. We need to clarify with Marc Morgan if / how we can use it.

**Comment by ehennestad** [comment]
Sounds good. Maybe better to use a no-reply specific to the data curation, i.e curation-noreply@ebrains.eu?

**Comment by eapapp** [comment]
I would stick to [no-reply@ebrains.eu](mailto:no-reply@ebrains.eu). We will add a message anyway about what the e-mail is about. Long addresses are harder to read and people may confuse it with the support address and try to reply (in vain).

**Comment by ehennestad** [comment]
This feature has been added as part of 588f2aa56aff2e4c90973d7ee91ed20f52f93cde
